<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Resursbank\Simplified\ViewModel\FetchAddress;

/** @var Template $block */
/** @var FetchAddress $viewModel */
/** @var Escaper $escaper */
if (isset($block)) {
    /** @noinspection PhpPossiblePolymorphicInvocationInspection */
    $viewModel = $block->getViewModel();
}
?>

<?php if (isset($escaper, $viewModel)): ?>
    <!--suppress JSUnusedLocalSymbols -->
    <script>
        require([
            // Add initialization module here.
        ], function(
            // Add initialization module here.
        ) {
            var initializationData = {
                privateCustomerType:
                    '<?= $escaper->escapeHtml($viewModel->getPrivateCustomerType()) ?>',
                companyCustomerType:
                    '<?= $escaper->escapeHtml($viewModel->getCompanyCustomerType()) ?>'
            }
        });
    </script>
<?php endif; ?>
