<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

namespace Resursbank\Simplified\Test\Unit\Model;

use JsonException;
use Magento\Framework\Exception\ValidatorException;
use Magento\Framework\TestFramework\Unit\Helper\ObjectManager;
use Magento\Payment\Gateway\Data\Order\OrderAdapter as Order;
use PHPUnit\Framework\TestCase;
use ReflectionException;
use ReflectionMethod;
use ReflectionObject;
use Resursbank\Core\Helper\PaymentMethods;
use Resursbank\Core\Model\PaymentMethod;
use Resursbank\Simplified\Model\ConfigProvider;

/**
 * Test cases designed for PaymentMethod data model.
 */
class ConfigProviderTest extends TestCase
{
    /**
     * @var ObjectManager
     */
    private $objectManager;

    /**
     * @var PaymentMethod
     */
    private $method;

    /**
     * @var ConfigProvider
     */
    private $configProvider;

    /**
     * @var PaymentMethods
     */
    private $helper;

    /**
     * Data utilised to mock PaymentMethod model instance.
     *
     * NOTE: maxOrderTotal should of course be max_order_total when applying
     * the data to the instance model. Naming it this way greatly simplifies
     * the comparison tests though.
     *
     * @var array
     */
    private $methodMockData = [
        'code' => 'invoice',
        'title' => 'Invoice',
        'maxOrderTotal' => 50000.0
    ];

    /**
     * @inheritDoc
     * @throws ValidatorException
     */
    protected function setUp(): void
    {
        $this->objectManager = new ObjectManager($this);

        $this->method = $this->objectManager->getObject(PaymentMethod::class);
        $this->method->setData($this->methodMockData)
            ->setMaxOrderTotal($this->methodMockData['maxOrderTotal']);

        $this->helper = $this->getMockBuilder(PaymentMethods::class)
            ->disableOriginalConstructor()
            ->setMethods(['getMethodsByCredentials'])
            ->getMock();

        $this->configProvider = $this->objectManager
            ->getObject(ConfigProvider::class, ['helper' => $this->helper]);
    }

    /**
     * Retrieve accessible mapPaymentMethod method mock.
     *
     * @return ReflectionMethod
     */
    private function getMapPaymentMethodMethod(): ReflectionMethod
    {
        $obj = new ReflectionObject($this->configProvider);
        $method = $obj->getMethod('mapPaymentMethod');
        $method->setAccessible(true);

        return $method;
    }

    /**
     * Assert that mapPaymentMethod works when provided with an object instance
     * containing raw data.
     *
     * @return void
     * @throws JsonException
     * @throws ReflectionException
     */
    public function testMapPaymentMethodWithRawData(): void
    {
        $raw = ['type' => 'card', 'specificType' => 'visa'];
        $this->method->setRaw(json_encode($raw, JSON_THROW_ON_ERROR));

        $data = $this->getMapPaymentMethodMethod()->invoke(
            $this->configProvider,
            $this->method
        );

        static::assertSame(array_merge($this->methodMockData, $raw), $data);
    }

    /**
     * Assert that mapPaymentMethod works when provided with an object instance
     * without raw data.
     *
     * @return void
     * @throws ReflectionException
     */
    public function testMapPaymentMethodWithoutRawData(): void
    {
        $raw = ['type' => '', 'specificType' => ''];

        $data = $this->getMapPaymentMethodMethod()->invoke(
            $this->configProvider,
            $this->method
        );

        static::assertSame(array_merge($this->methodMockData, $raw), $data);
    }

    /**
     * Assert that mapPaymentMethod throws and instance of JsonException when
     * provided with an object instance containing corrupt raw data.
     *
     * @return void
     * @throws ReflectionException
     */
    public function testMapPaymentMethodThrowsWithCorruptRawData(): void
    {
        $this->expectException(JsonException::class);

        $this->method->setRaw('that does not take wooden nickels');

        $this->getMapPaymentMethodMethod()->invoke(
            $this->configProvider,
            $this->method
        );
    }

    /**
     * @throws JsonException
     */
    public function testGetConfigResult(): void
    {
        // Data which should be generated by the getConfig method.
        $data = [
            [
                'code' => 'partpayment',
                'title' => 'Delbetalning',
                'maxOrderTotal' => 543.00,
                'type' => '',
                'specificType' => ''
            ],
            [
                'code' => 'some_method_12314',
                'title' => 'Some method',
                'maxOrderTotal' => 6054.20,
                'type' => 'resursCard',
                'specificType' => 'internal'
            ]
        ];

        $expected = [
            'payment' => [
                'resursbank_simplified' => [
                    'methods' => $data
                ]
            ]
        ];

        // Create mocked PaymentMethod model instances, utilising $data.
        $method1 = $this->objectManager->getObject(PaymentMethod::class);
        $method1->setData($data[0])
            ->setMaxOrderTotal($data[0]['maxOrderTotal']);

        $method2 = $this->objectManager->getObject(PaymentMethod::class);
        $method2->setData($data[1])
            ->setMaxOrderTotal($data[1]['maxOrderTotal'])
            ->setRaw(json_encode(
                ['type' => 'resursCard', 'specificType' => 'internal'],
                JSON_THROW_ON_ERROR
            ));

        // Mock response from method that collects payment methods from DB.
        $this->helper
            ->expects(static::once())
            ->method('getMethodsByCredentials')
            ->willReturn([$method1, $method2]);

        // Assert the value returned by getConfig matches out expectation.
        static::assertSame($expected, $this->configProvider->getConfig());
    }
}
